name: Deploy to GitHub Pages

on:
  push:
    branches: "main" # Change to "master" if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build App
        run: npm run build
        
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Change to ./build if using Create React App instead of Vite

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
    permissions:
      pages: write
      id-token: write
